module.exports = {
  port: 3000,
  eventsMaxListeners: 100,
  appDir: 'app',
  configDir: 'config',
  modulesDir: 'app/modules',
  publicDir: 'public',
  uploadsDir: 'public/uploads',
  policiesDir: 'app/policies',
  localesDir: 'app/locales',
  dbAdaptersDir: 'app/db/adapters',
  dbMigrationsDir: 'app/db/migrations',
  secretKeys: ['replace me 1', 'replace me 2'],
  bcryptSaltRounds: 10,
  modules: {
    configFile: 'config.js',
    viewsDir: 'views',
    defaultView: 'index',
    controllersDir: 'controllers',
    modelsDir: 'models',
    servicesDir: 'services',
    helpersDir: 'helpers',
    clientDir: 'client',
    adminClientConfigFile: 'adminClientConfig.js',
  },
  views: {
    defaultPageTitle: 'Taboo CMS',
    extension: 'html',
    layoutsDir: 'app/templates/layouts',
    defaultLayout: 'default',
    errorsDir: 'app/templates/error',
    defaultErrorLayout: 'error',
    defaultErrorView: 'index',
  },
  session: {
    store: 'cookie', // 'cookie' || CustomSessionClass
    options: {
      key: 'taboo.sid',
      maxAge: 86400000, // ms = 1 day
      autoCommit: true,
      overwrite: true,
      httpOnly: true,
      signed: true,
      rolling: true,
      renew: false,
      secure: false,
      encrypt: true,
    },
  },
  silentErrors: ['UnauthorizedError', 'BadRequestError', 'ForbiddenError', 'ValidationError', 'NotFoundError'],
  ejsOptions: {
    root: `${process.cwd()}/app/modules/`,
  },
};
